# Generated by Django 2.1.3 on 2018-12-07 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='social_id',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
    ]
