# Generated by Django 2.1.3 on 2018-12-11 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_is_verified'),
        ('authentication', '0002_user_social_id'),
    ]

    operations = [
    ]
