# Generated by Django 2.1.3 on 2018-12-11 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_is_verified'),
        ('authentication', '0003_merge_20181211_0940'),
    ]

    operations = [
    ]
