<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
# Generated by Django 2.1.3 on 2018-12-17 13:16
=======
=======
>>>>>>> feat(like_dislike): adjust migrations
<<<<<<< HEAD
# Generated by Django 2.1.3 on 2018-12-17 10:21
=======
=======
>>>>>>> feat(like_dislike): adjust migrations
<<<<<<< HEAD
# Generated by Django 2.1.3 on 2018-12-13 10:57
=======
# Generated by Django 2.1.3 on 2018-12-12 19:30
>>>>>>> feat(like_dislike): add model and serializer classes
<<<<<<< HEAD
>>>>>>> feat(like_dislike): add model and serializer classes
<<<<<<< HEAD
>>>>>>> feat(like_dislike): add model and serializer classes
=======
=======
=======
# Generated by Django 2.1.3 on 2018-12-13 05:59
>>>>>>> feat(like_dislike): adjust migrations
>>>>>>> feat(like_dislike): adjust migrations
>>>>>>> feat(like_dislike): adjust migrations
=======
# Generated by Django 2.1.3 on 2018-12-17 11:18
>>>>>>>  feat(like_dislike): resolve conflicts
=======
# Generated by Django 2.1.3 on 2018-12-17 13:00
>>>>>>>  feat(like_dislike): fix conflicts

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followed_user_id', to=settings.AUTH_USER_MODEL)),
                ('follower', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follower_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('image', models.URLField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
