# Generated by Django 2.1.3 on 2018-12-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='tittle',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
    ]
