# Generated by Django 2.1.3 on 2018-12-20 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('articles', '0002_auto_20181220_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(db_index=True, max_length=255)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Article')),
                ('article_slug', models.ForeignKey(db_column='slug', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='a_slug', to='articles.Article', to_field='slug')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
            ],
            options={
                'ordering': ['-reported_at'],
            },
        ),
    ]
