# Generated by Django 2.1.3 on 2018-12-18 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20181218_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='readTime',
            field=models.IntegerField(default=0),
        ),
    ]
