# Generated by Django 2.1.3 on 2018-12-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20181211_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleimg',
            name='image',
            field=models.CharField(default='', max_length=255),
        ),
    ]
