# Generated by Django 2.1.3 on 2018-12-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20181211_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleimg',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
