# Generated by Django 2.1.3 on 2018-12-11 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20181211_1214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articleimg',
            old_name='image',
            new_name='image_url',
        ),
    ]
